name: Build and deploy dotnet core project to Azure Function App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  #AZURE_FUNCTIONAPP_PACKAGE_PATH  
  AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO: './MedicalHealth.Fiap.Function.Persistencia.Atualizar.AgendaMedico'
  AZURE_FUNCTIONAPP_CRIAR_CONSULTA: './MedicalHealth.Fiap.Function.Persistencia.Criar.Consulta'
  AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA: './MedicalHealth.Fiap.Function.Persistencia.Atualizar.Consulta'
  #AZURE_FUNCTIONAPP_CRIAR_USUARIO: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  #AZURE_FUNCTIONAPP_ATUALIZAR_USUARIO: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  #AZURE_FUNCTIONAPP_CRIAR_MEDICO: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  #AZURE_FUNCTIONAPP_ATUALIZAR_MEDICO: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  #AZURE_FUNCTIONAPP_CRIAR_PACIENTE: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  #AZURE_FUNCTIONAPP_ATUALIZAR_PACIENTE: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Build e Publish API
        run: |
          dotnet publish MedicalHealth.Fiap.API -c Release -o app

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configurar Storage API no Azure
        run: |
          az webapp config appsettings set --resource-group "Hackathon" --name "hackathonapigrupo12" \
          --settings AZURE_WEBJOBS_STORAGE=${{ secrets.AZURE_WEBJOBS_STORAGE }}

      - name: Deploy Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hackathonapigrupo12'
          slot-name: 'Production'
          package: app
         
      - name: 'Debug - List Repository Structure'
        run: |
          echo "📂 Listando arquivos no diretório atual:"
          pwd
          ls -R
  
      - name: 'Resolver Dependencias FUNCTION_CRIAR_AGENDAMEDICO'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO }}'
          dotnet restore
          dotnet build --configuration Release --output ./output/criaragendamedico
          popd
  
      - name: 'Publicar FUNCTION_CRIAR_AGENDAMEDICO'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO }}'
          dotnet publish --configuration Release --output ./output/criaragendamedico
          popd
  
      - name: 'Rodar Action FUNCTION_CRIAR_AGENDAMEDICO'
        uses: Azure/functions-action@v1
        id: fa-criar-agenda
        with:
          app-name: 'FunctionPersistenciaCriarAgendaMedico'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO }}/output/criaragendamedico'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_38DD225916C44C9EB6239E4C35905D96 }}

      ##################################################################################################################################
      ##################################################################################################################################

      - name: 'Resolver Dependencias FUNCTION_ATUALIZAR_AGENDAMEDICO'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}'
          dotnet restore
          dotnet build --configuration Release --output ./output/atualizaragendamedico
          popd
  
      - name: 'Publicar FUNCTION_ATUALIZAR_AGENDAMEDICO'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}'
          dotnet publish --configuration Release --output ./output/atualizaragendamedico
          popd
      
      - name: 'Rodar Action FUNCTION_ATUALIZAR_AGENDAMEDICO'
        uses: Azure/functions-action@v1
        id: fa-atualizar-agenda
        with:
          app-name: 'FunctionPersistenciaAtualizarAgendaMedico'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}/output/atualizaragendamedico'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_399629F90EF5456692CF3972F1AE7ECD }}
  
      - name: 'Limpar Diretorio FUNCTION_ATUALIZAR_AGENDAMEDICO'
        shell: bash
        run: |
          rm -rf '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}/output/atualizaragendamedico'

      ##################################################################################################################################
      ##################################################################################################################################  
      #

      - name: 'Resolver Dependencias FUNCTION_ATUALIZAR_CONSULTA'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA }}'
          dotnet restore
          dotnet build --configuration Release --output ./output/atualizarconsulta
          popd
  
      - name: 'Publicar FUNCTION_ATUALIZAR_CONSULTA'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA }}'
          dotnet publish --configuration Release --output ./output/atualizarconsulta
          popd
      
      - name: 'Rodar Action FUNCTION_ATUALIZAR_CONSULTA'
        uses: Azure/functions-action@v1
        id: fa-atualizar-consulta
        with:
          app-name: 'FunctionPersistenciaAtualizarConsulta'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA }}/output/atualizarconsulta'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_272C1F31E9C84716B19BB7BA813E23F7 }}
  
      - name: 'Limpar Diretorio FUNCTION_ATUALIZAR_CONSULTA'
        shell: bash
        run: |
          rm -rf '${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}/output/atualizarconsulta'

      - name: Logout do Azure
        run: az logout
