name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Build e Publish API
        run: |
          dotnet publish MedicalHealth.Fiap.API -c Release -o app

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configurar Storage no Azure
        run: |
          az webapp config appsettings set --resource-group "Hackathon" --name "hackathonapigrupo12" \
          --settings AZURE_WEBJOBS_STORAGE=${{ secrets.AZURE_WEBJOBS_STORAGE }}

      - name: Deploy direto para o Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hackathonapigrupo12'
          slot-name: 'Production'
          package: app

      - name: Logout do Azure
        run: az logout
