name: Build and deploy ASP.Net Core app to Azure Web App - hackathonapigrupo12

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish MedicalHealth.Fiap.API -c Release -o ${{github.workspace}}/publish/api

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: ${{github.workspace}}/publish/api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-api

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hackathonapigrupo12'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{github.workspace}}/publish/api
