name: Build and deploy dotnet core project to Azure Function App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  # Diretórios dos projetos (certifique-se de que os nomes estejam corretos)
  AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO: './MedicalHealth.Fiap.Function.Persistencia.AgendaMedico'
  AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO: './MedicalHealth.Fiap.Function.Persistencia.Atualizar.AgendaMedico'
  AZURE_FUNCTIONAPP_CRIAR_CONSULTA: './MedicalHealth.Fiap.Function.Persistencia.Criar.Consulta'
  AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA: './MedicalHealth.Fiap.Function.Persistencia.Atualizar.Consulta'
  AZURE_FUNCTIONAPP_CRIAR_USUARIO: './MedicalHealth.Fiap.Function.Pesistencia.Criar.Usuario'
  AZURE_FUNCTIONAPP_ATUALIZAR_USUARIO: './MedicalHealth.Fiap.Function.Pesistencia.Atualizar.Usuario'
  AZURE_FUNCTIONAPP_CRIAR_MEDICO: './MedicalHealth.Fiap.Function.Pesistencia.Criar.Medico'
  AZURE_FUNCTIONAPP_ATUALIZAR_MEDICO: './MedicalHealth.Fiap.Function.Pesistencia.Atualizar.Medico'
  AZURE_FUNCTIONAPP_CRIAR_PACIENTE: './MedicalHealth.Fiap.Function.Pesistencia.Criar.Paciente'
  AZURE_FUNCTIONAPP_ATUALIZAR_PACIENTE: './MedicalHealth.Fiap.Function.Pesistencia.Atualizar.Paciente'
  DOTNET_VERSION: '8.0.x'

jobs:
  ####################################################################################################
  # BUILD DOS PROJETOS
  ####################################################################################################
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build e Publish da API
        run: |
          dotnet publish MedicalHealth.Fiap.API -c Release -o ./output/api
      - name: Upload dos Artefatos da API
        uses: actions/upload-artifact@v3
        with:
          name: api-build
          path: ./output/api

  build-function-criar-agendamento:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_CRIAR_AGENDAMEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/criaragendamedico
          popd

  build-function-atualizar-agendamento:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_ATUALIZAR_AGENDAMEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/atualizaragendamedico
          popd

  build-function-criar-consulta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_CRIAR_CONSULTA
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_CONSULTA }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/criarconsulta
          popd

  build-function-atualizar-consulta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_ATUALIZAR_CONSULTA
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/atualizarconsulta
          popd

  build-function-criar-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_CRIAR_USUARIO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_USUARIO }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/criarusuario
          popd

  build-function-atualizar-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_ATUALIZAR_USUARIO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_USUARIO }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/atualizarusuario
          popd

  build-function-criar-medico:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_CRIAR_MEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_MEDICO }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/criarmedico
          popd

  build-function-atualizar-medico:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_ATUALIZAR_MEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_MEDICO }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/atualizarmedico
          popd

  build-function-criar-paciente:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_CRIAR_PACIENTE
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_PACIENTE }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/criarpaciente
          popd

  build-function-atualizar-paciente:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build FUNCTION_ATUALIZAR_PACIENTE
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_PACIENTE }}"
          dotnet restore
          dotnet build --configuration Release --output ./output/atualizarpaciente
          popd

  ####################################################################################################
  # DEPLOY DOS PROJETOS
  ####################################################################################################
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Configurar Storage da API
        run: |
          az webapp config appsettings set --resource-group "Hackathon" --name "hackathonapigrupo12" \
          --settings AZURE_WEBJOBS_STORAGE=${{ secrets.AZURE_WEBJOBS_STORAGE }}
      - name: Deploy da Azure Web App (API)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hackathonapigrupo12'
          slot-name: 'Production'
          package: ./output/api
      - name: Logout do Azure
        run: az logout

  deploy-criar-agendamento:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_CRIAR_AGENDAMEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO }}"
          dotnet publish --configuration Release --output ./output/criaragendamedico
          popd
      - name: Deploy FUNCTION_CRIAR_AGENDAMEDICO
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaCriarAgendaMedico'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO }}/output/criaragendamedico"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_38DD225916C44C9EB6239E4C35905D96 }}
      - name: Limpar Diretorio de Output FUNCTION_CRIAR_AGENDAMEDICO
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_CRIAR_AGENDAMEDICO }}/output/criaragendamedico"

  deploy-atualizar-agendamento:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_ATUALIZAR_AGENDAMEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}"
          dotnet publish --configuration Release --output ./output/atualizaragendamedico
          popd
      - name: Deploy FUNCTION_ATUALIZAR_AGENDAMEDICO
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaAtualizarAgendaMedico'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}/output/atualizaragendamedico"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_399629F90EF5456692CF3972F1AE7ECD }}
      - name: Limpar Diretorio de Output FUNCTION_ATUALIZAR_AGENDAMEDICO
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_AGENDAMEDICO }}/output/atualizaragendamedico"

  deploy-criar-consulta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_CRIAR_CONSULTA
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_CONSULTA }}"
          dotnet publish --configuration Release --output ./output/criarconsulta
          popd
      - name: Deploy FUNCTION_CRIAR_CONSULTA
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaCriarConsulta'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_CRIAR_CONSULTA }}/output/criarconsulta"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A896A7CF00A04A1E9927857B3A8FAE7E }}
      - name: Limpar Diretorio de Output FUNCTION_CRIAR_CONSULTA
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_CRIAR_CONSULTA }}/output/criarconsulta"

  deploy-atualizar-consulta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_ATUALIZAR_CONSULTA
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA }}"
          dotnet publish --configuration Release --output ./output/atualizarconsulta
          popd
      - name: Deploy FUNCTION_ATUALIZAR_CONSULTA
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaAtualizarConsulta'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA }}/output/atualizarconsulta"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_272C1F31E9C84716B19BB7BA813E23F7 }}
      - name: Limpar Diretorio de Output FUNCTION_ATUALIZAR_CONSULTA
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_CONSULTA }}/output/atualizarconsulta"

  deploy-criar-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_CRIAR_USUARIO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_USUARIO }}"
          dotnet publish --configuration Release --output ./output/criarusuario
          popd
      - name: Deploy FUNCTION_CRIAR_USUARIO
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaCriarUsuario'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_CRIAR_USUARIO }}/output/criarusuario"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6EFBA21EBAC946D68E226057B7B25234 }}
      - name: Limpar Diretorio de Output FUNCTION_CRIAR_USUARIO
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_CRIAR_USUARIO }}/output/criarusuario"

  deploy-atualizar-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_ATUALIZAR_USUARIO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_USUARIO }}"
          dotnet publish --configuration Release --output ./output/atualizarusuario
          popd
      - name: Deploy FUNCTION_ATUALIZAR_USUARIO
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaAtualizarUsuario'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_USUARIO }}/output/atualizarusuario"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_60A79874E145407A8E97BFCA08FFD84F }}
      - name: Limpar Diretorio de Output FUNCTION_ATUALIZAR_USUARIO
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_USUARIO }}/output/atualizarusuario"

  deploy-criar-medico:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_CRIAR_MEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_MEDICO }}"
          dotnet publish --configuration Release --output ./output/criarmedico
          popd
      - name: Deploy FUNCTION_CRIAR_MEDICO
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaCriarMedico'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_CRIAR_MEDICO }}/output/criarmedico"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CRIAR_MEDICO }}
      - name: Limpar Diretorio de Output FUNCTION_CRIAR_MEDICO
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_CRIAR_MEDICO }}/output/criarmedico"

  deploy-atualizar-medico:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_ATUALIZAR_MEDICO
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_MEDICO }}"
          dotnet publish --configuration Release --output ./output/atualizarmedico
          popd
      - name: Deploy FUNCTION_ATUALIZAR_MEDICO
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaAtualizarMedico'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_MEDICO }}/output/atualizarmedico"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ATUALIZAR_MEDICO }}
      - name: Limpar Diretorio de Output FUNCTION_ATUALIZAR_MEDICO
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_MEDICO }}/output/atualizarmedico"

  deploy-criar-paciente:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_CRIAR_PACIENTE
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_CRIAR_PACIENTE }}"
          dotnet publish --configuration Release --output ./output/criarpaciente
          popd
      - name: Deploy FUNCTION_CRIAR_PACIENTE
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaCriarPaciente'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_CRIAR_PACIENTE }}/output/criarpaciente"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CRIAR_PACIENTE }}
      - name: Limpar Diretorio de Output FUNCTION_CRIAR_PACIENTE
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_CRIAR_PACIENTE }}/output/criarpaciente"

  deploy-atualizar-paciente:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publicar FUNCTION_ATUALIZAR_PACIENTE
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_PACIENTE }}"
          dotnet publish --configuration Release --output ./output/atualizarpaciente
          popd
      - name: Deploy FUNCTION_ATUALIZAR_PACIENTE
        uses: Azure/functions-action@v1
        with:
          app-name: 'FunctionPersistenciaAtualizarPaciente'
          slot-name: 'Production'
          package: "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_PACIENTE }}/output/atualizarpaciente"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ATUALIZAR_PACIENTE }}
      - name: Limpar Diretorio de Output FUNCTION_ATUALIZAR_PACIENTE
        run: |
          rm -rf "${{ env.AZURE_FUNCTIONAPP_ATUALIZAR_PACIENTE }}/output/atualizarpaciente"
