name: Build and deploy ASP.Net Core app to Azure Web App - hackathonapigrupo12

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Build and publish API only
        run: |
          dotnet publish MedicalHealth.Fiap.API -c Release -o $GITHUB_WORKSPACE/publish/api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: $GITHUB_WORKSPACE/publish/api

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: $GITHUB_WORKSPACE/publish/api

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hackathonapigrupo12'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: $GITHUB_WORKSPACE/publish/api
